<?php

return [
    [
        'prefix' => 'info',
        'title' => 'Сведения об образовательной организации',
        'items' => [
            ['name' => 'Основные сведения', 'route' => 'info::basics'],
            ['name' => 'Структура и органы управления образовательной организацией', 'route' => 'info::structure'],
            ['name' => 'Документы', 'route' => 'docs::index'],
            ['name' => 'Образование', 'route' => 'specials::index'],
            ['name' => 'Руководство и педагогический состав', 'route' => 'staff::index'],
            ['name' => 'Материально-техническое обеспечение и оснащённость образовательного процесса', 'route' => 'info::mtResources'],
            ['name' => 'Платные образовательные услуги', 'route' => 'info::paidServices'],
            ['name' => 'Финансово-хозяйственная деятельность', 'route' => 'info::finance'],
            ['name' => 'Вакантные места для приема (перевода) обучающихся', 'route' => 'info::vacancies'],
            ['name' => 'Стипендии и меры поддержки обучающихся', 'route' => 'info::scholarships'],
            ['name' => 'Организация питания в образовательной организации', 'route' => 'info::catering'],
            ['name' => 'Образовательные стандарты и требования', 'route' => 'info::standards'],
        ],
    ],
    [
        'prefix' => 'college',
        'title' => 'О колледже',
        'items' => [
            ['name' => 'Сведения об образовательном учреждении', 'route' => 'info::basics'],
            ['name' => 'Специальности', 'route' => 'specials::index'],
            ['name' => 'Структура', 'route' => 'college::structure'],
            ['name' => 'Руководство и педагогический состав', 'route' => 'staff::index'],
            ['name' => 'Новости', 'route' => 'news::index'],
            ['name' => 'История', 'route' => 'college::history'],
            ['name' => 'Устав', 'route' => 'college::charter'],
            ['name' => 'Контакты', 'route' => 'contacts::index'],
            ['name' => 'Вакансии', 'route' => 'college::vacancies'],
            ['name' => 'Виртуальный тур', 'route' => 'college::virtualTour'],
        ],
    ],
    [
        'prefix' => 'abiturients',
        'title' => 'Абитуриентам',
        'items' => [
            ['name' => 'Приемная комиссия', 'route' => 'abiturients::admissionCommittee'],
            ['name' => 'Правила и условия приема', 'route' => 'abiturients::admissionRules'],
            ['name' => 'Специальности', 'route' => 'specials::index'],
            ['name' => 'Платное обучение', 'route' => 'abiturients::paidEducation'],
            ['name' => 'Общежитие', 'route' => 'abiturients::dormitory'],
            ['name' => 'Медицинские осмотры', 'route' => 'abiturients::medicalExams'],
            ['name' => 'Информация о количестве поданных заявлений', 'route' => 'abiturients::applicationInfo'],
            ['name' => 'Документы', 'route' => 'abiturients::documents'],
            ['name' => 'Вопросы-ответы', 'route' => 'abiturients::faq'],
            ['name' => 'Расписание вступительных испытаний по Пожарной Безопасности', 'route' => 'abiturients::examSchedule'],
            ['name' => 'Результаты вступительных испытаний абитуриентов', 'route' => 'abiturients::examResults'],
            ['name' => 'Приказ на зачисление', 'route' => 'abiturients::enrollmentOrder'],
            ['name' => 'Список лиц рекомендованных к зачислению', 'route' => 'abiturients::recommendedList'],
        ],
    ],
    [
        'prefix' => 'students',
        'title' => 'Студентам',
        'items' => [
            ['name' => 'Правила внутреннего распорядка', 'route' => 'students::internalRules'],
            ['name' => 'Информация о ЕГЭ', 'route' => 'students::examInfo'],
            ['name' => 'Твоя безопасность', 'route' => 'students::safety'],
            ['name' => 'Борьба с экстремизмом', 'route' => 'students::extremism'],
            ['name' => 'Борьба с коррупцией', 'route' => 'students::corruption'],
            ['name' => 'Трудоустройство выпускников', 'route' => 'students::employment'],
            ['name' => 'Вакансии для выпускников', 'route' => 'students::vacancies'],
            ['name' => 'Расписание', 'route' => 'students::schedule'],
        ],
    ],
    [
        'prefix' => 'additional_education',
        'title' => 'Дополнительное образование',
        'items' => [
            ['name' => 'Документы', 'route' => 'additional_education::documents'],
            ['name' => 'Программы повышения квалификации и профессиональной переподготовки', 'route' => 'additional_education::qualificationPrograms'],
            ['name' => 'Программы профессионального обучения', 'route' => 'additional_education::professionalPrograms'],
            ['name' => 'Дополнительное образование детей и взрослых', 'route' => 'additional_education::childrenAndAdults'],
            ['name' => 'Обучение лиц, пострадавших от последствий распространения коронавирусной инфекции', 'route' => 'additional_education::covidTraining'],
            ['name' => 'Объявления', 'route' => 'additional_education::announcements'],
        ],
    ],
];
